version: '3.8'
services:
  devenv:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    environment:
      - MOGLI_DB_HOST=db.mogli.local
      - MOGLI_DB_PORT=5432
      - MOGLI_DB_USER=postgres
      - MOGLI_DB_PASSWORD=postgres
      - MOGLI_DB_NAME=mogli
    links:
      - "db:db.mogli.local"
      - "auth:auth.mogli.local"
    extra_hosts:
      - "api.mogli.local:127.0.0.1"
    depends_on:
      - db
      - auth
  db:
    image: postgres:15.3-alpine3.18
    restart: always
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=mogli
    ports:
     - "5432:5432"
  auth:
    image: quay.io/keycloak/keycloak:21.1.1
    restart: always
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    command:
      - start-dev
