FROM ubuntu:22.04


########################################################################################################################
# Install Dependencies                                                                                                 #
########################################################################################################################
USER root
RUN apt-get update
RUN apt-get -y install g++-12 cmake git

# Needed for the dev environment
RUN apt-get -y install cppcheck

# Dependencies
RUN apt-get -y install libiddawc-dev
