FROM ubuntu:23.04


########################################################################################################################
# Install Dependencies                                                                                                 #
########################################################################################################################
USER root
# only needed for add-apt-repository
RUN apt-get update && apt-get install -y software-properties-common
RUN add-apt-repository ppa:ubuntu-toolchain-r/test && apt-get update
RUN apt-get -y install g++-13 cmake git

# Needed for the dev environment
RUN apt-get -y install cppcheck doxygen graphviz gdb

# Dependencies
RUN apt-get -y install libiddawc-dev libpq-dev
